<a href="https://colab.research.google.com/github/2303A51929/1929_batch-30_PDS/blob/main/lab3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

question1


In [2]:
import numpy as np

test_scores = np.random.randint(0, 101, size=(4, 4))
print(test_scores)

column_means = np.mean(test_scores, axis=0)
row_means = np.mean(test_scores, axis=1)

print("Column-wise means:", column_means)
print("Row-wise means:", row_means)

std_dev = np.std(test_scores)
variance = np.var(test_scores)

print("Standard Deviation:", std_dev)
print("Variance:", variance)

min_value = np.min(test_scores)
max_value = np.max(test_scores)
min_index = np.argmin(test_scores)
max_index = np.argmax(test_scores)

print("Minimum value:", min_value)
print("Maximum value:", max_value)
print("Index of minimum value:", min_index)
print("Index of maximum value:", max_index)

[[52 65 57  9]
 [37 20  3 99]
 [89 20  6 76]
 [91 19 22  1]]
Column-wise means: [67.25 31.   22.   46.25]
Row-wise means: [45.75 39.75 47.75 33.25]
Standard Deviation: 32.95427703652441
Variance: 1085.984375
Minimum value: 1
Maximum value: 99
Index of minimum value: 15
Index of maximum value: 7


question 2


In [6]:
rgb_image = np.random.randint(0, 256, size=(3, 3, 3))
print(rgb_image)
red_channel = rgb_image[:, :, 0]
green_channel = rgb_image[:, :, 1]
blue_channel = rgb_image[:, :, 2]

print("Red Channel:\n", red_channel)
print("Green Channel:\n", green_channel)
print("Blue Channel:\n", blue_channel)
red_mean = np.mean(red_channel)
green_mean = np.mean(green_channel)
blue_mean = np.mean(blue_channel)

print(f"Average pixel intensity for Red channel: {red_mean}")
print(f"Average pixel intensity for Green channel: {green_mean}")
print(f"Average pixel intensity for Blue channel: {blue_mean}")
brightness_increase = 50
brightened_image = np.clip(rgb_image + brightness_increase, 0, 255)
print("Brightened Image (clipped at 255):\n", brightened_image)

[[[101  37 198]
  [105  72  48]
  [158 247 162]]

 [[239 135   4]
  [161 150 155]
  [122  11  87]]

 [[ 40  51 180]
  [177 118 181]
  [189  81   1]]]
Red Channel:
 [[101 105 158]
 [239 161 122]
 [ 40 177 189]]
Green Channel:
 [[ 37  72 247]
 [135 150  11]
 [ 51 118  81]]
Blue Channel:
 [[198  48 162]
 [  4 155  87]
 [180 181   1]]
Average pixel intensity for Red channel: 143.55555555555554
Average pixel intensity for Green channel: 100.22222222222223
Average pixel intensity for Blue channel: 112.88888888888889
Brightened Image (clipped at 255):
 [[[151  87 248]
  [155 122  98]
  [208 255 212]]

 [[255 185  54]
  [211 200 205]
  [172  61 137]]

 [[ 90 101 230]
  [227 168 231]
  [239 131  51]]]
